#!/usr/bin/env bash
cd ./config-server/
mvn  docker:removeImage
cd ../gateway/
mvn  docker:removeImage
cd ../register-center1/
mvn  docker:removeImage
cd ../register-center2/
mvn  docker:removeImage
cd ../ucenter/
mvn  docker:removeImage
cd ../upms/
mvn  docker:removeImage
cd ../oauth/
mvn  docker:removeImage
cd ../monitor-turbine/
mvn  docker:removeImage
cd ../monitor-zipkin/
